version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2019-08-07T01-59-21Z
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: s3key
      MINIO_SECRET_KEY: s3secret
    command: server /data
    
  ftp:
    image: afharo/pure-ftp
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
    volumes:
      - './.tmp/ftp:/home/ftpusers/test'
    environment:
      - 'PUBLICHOST=192.168.99.100'
