name: Release
on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-code-dependencies-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-code-dependencies

      - run: |
          go get github.com/NoUseFreak/go-vembed/vembed

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
